global using NUnit.Framework;
global using Moq;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.Extensions.Logging;
global using WebApplication1.Controllers;
global using System.Collections.Generic;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.AspNetCore.Http;
global using System.Threading.Tasks;